sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '10'
  - '12'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
notifications:
  slack: norch:wLsHiXjnAH5BdtTq3qtAqGp7